<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="generator" content="pandoc">
  <title>Principal component analysis</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="06_pca_files/reveal.js-3.3.0.1/css/reveal.css"/>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    background-color: #ffffff;
    color: #a0a0a0;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #a0a0a0;  padding-left: 4px; }
div.sourceCode
  { color: #1f1c1b; background-color: #ffffff; }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span. { color: #1f1c1b; } /* Normal */
code span.al { color: #bf0303; background-color: #f7e6e6; font-weight: bold; } /* Alert */
code span.an { color: #ca60ca; } /* Annotation */
code span.at { color: #0057ae; } /* Attribute */
code span.bn { color: #b08000; } /* BaseN */
code span.bu { color: #644a9b; font-weight: bold; } /* BuiltIn */
code span.cf { color: #1f1c1b; font-weight: bold; } /* ControlFlow */
code span.ch { color: #924c9d; } /* Char */
code span.cn { color: #aa5500; } /* Constant */
code span.co { color: #898887; } /* Comment */
code span.cv { color: #0095ff; } /* CommentVar */
code span.do { color: #607880; } /* Documentation */
code span.dt { color: #0057ae; } /* DataType */
code span.dv { color: #b08000; } /* DecVal */
code span.er { color: #bf0303; text-decoration: underline; } /* Error */
code span.ex { color: #0095ff; font-weight: bold; } /* Extension */
code span.fl { color: #b08000; } /* Float */
code span.fu { color: #644a9b; } /* Function */
code span.im { color: #ff5500; } /* Import */
code span.in { color: #b08000; } /* Information */
code span.kw { color: #1f1c1b; font-weight: bold; } /* Keyword */
code span.op { color: #1f1c1b; } /* Operator */
code span.ot { color: #006e28; } /* Other */
code span.pp { color: #006e28; } /* Preprocessor */
code span.re { color: #0057ae; background-color: #e0e9f8; } /* RegionMarker */
code span.sc { color: #3daee9; } /* SpecialChar */
code span.ss { color: #ff5500; } /* SpecialString */
code span.st { color: #bf0303; } /* String */
code span.va { color: #0057ae; } /* Variable */
code span.vs { color: #bf0303; } /* VerbatimString */
code span.wa { color: #bf0303; } /* Warning */
</style>

<link rel="stylesheet" href="06_pca_files/reveal.js-3.3.0.1/css/theme/moon.css" id="theme">

<style type="text/css">
.reveal section img {
  background: rgba(255, 255, 255, 0.85);
}
</style>

  <!-- some tweaks to reveal css -->
  <style type="text/css">
    .reveal h1 { font-size: 2.0em; }
    .reveal h2 { font-size: 1.5em;  }
    .reveal h3 { font-size: 1.25em;	}
    .reveal h4 { font-size: 1em;	}

    .reveal .slides>section,
    .reveal .slides>section>section {
      padding: 0px 0px;
    }



    .reveal table {
      border-width: 1px;
      border-spacing: 2px;
      border-style: dotted;
      border-color: gray;
      border-collapse: collapse;
      font-size: 0.7em;
    }

    .reveal table th {
      border-width: 1px;
      padding-left: 10px;
      padding-right: 25px;
      font-weight: bold;
      border-style: dotted;
      border-color: gray;
    }

    .reveal table td {
      border-width: 1px;
      padding-left: 10px;
      padding-right: 25px;
      border-style: dotted;
      border-color: gray;
    }


  </style>

    <style type="text/css">code{white-space: pre;}</style>

    <link rel="stylesheet" href="styles.css"/>

<!-- Printing and PDF exports -->
<script id="paper-css" type="application/dynamic-css">

/* Default Print Stylesheet Template
   by Rob Glazebrook of CSSnewbie.com
   Last Updated: June 4, 2008

   Feel free (nay, compelled) to edit, append, and
   manipulate this file as you see fit. */


@media print {

	/* SECTION 1: Set default width, margin, float, and
	   background. This prevents elements from extending
	   beyond the edge of the printed page, and prevents
	   unnecessary background images from printing */
	html {
		background: #fff;
		width: auto;
		height: auto;
		overflow: visible;
	}
	body {
		background: #fff;
		font-size: 20pt;
		width: auto;
		height: auto;
		border: 0;
		margin: 0 5%;
		padding: 0;
		overflow: visible;
		float: none !important;
	}

	/* SECTION 2: Remove any elements not needed in print.
	   This would include navigation, ads, sidebars, etc. */
	.nestedarrow,
	.controls,
	.fork-reveal,
	.share-reveal,
	.state-background,
	.reveal .progress,
	.reveal .backgrounds {
		display: none !important;
	}

	/* SECTION 3: Set body font face, size, and color.
	   Consider using a serif font for readability. */
	body, p, td, li, div {
		font-size: 20pt!important;
		font-family: Georgia, "Times New Roman", Times, serif !important;
		color: #000;
	}

	/* SECTION 4: Set heading font face, sizes, and color.
	   Differentiate your headings from your body text.
	   Perhaps use a large sans-serif for distinction. */
	h1,h2,h3,h4,h5,h6 {
		color: #000!important;
		height: auto;
		line-height: normal;
		font-family: Georgia, "Times New Roman", Times, serif !important;
		text-shadow: 0 0 0 #000 !important;
		text-align: left;
		letter-spacing: normal;
	}
	/* Need to reduce the size of the fonts for printing */
	h1 { font-size: 28pt !important;  }
	h2 { font-size: 24pt !important; }
	h3 { font-size: 22pt !important; }
	h4 { font-size: 22pt !important; font-variant: small-caps; }
	h5 { font-size: 21pt !important; }
	h6 { font-size: 20pt !important; font-style: italic; }

	/* SECTION 5: Make hyperlinks more usable.
	   Ensure links are underlined, and consider appending
	   the URL to the end of the link for usability. */
	a:link,
	a:visited {
		color: #000 !important;
		font-weight: bold;
		text-decoration: underline;
	}
	/*
	.reveal a:link:after,
	.reveal a:visited:after {
		content: " (" attr(href) ") ";
		color: #222 !important;
		font-size: 90%;
	}
	*/


	/* SECTION 6: more reveal.js specific additions by @skypanther */
	ul, ol, div, p {
		visibility: visible;
		position: static;
		width: auto;
		height: auto;
		display: block;
		overflow: visible;
		margin: 0;
		text-align: left !important;
	}
	.reveal pre,
	.reveal table {
		margin-left: 0;
		margin-right: 0;
	}
	.reveal pre code {
		padding: 20px;
		border: 1px solid #ddd;
	}
	.reveal blockquote {
		margin: 20px 0;
	}
	.reveal .slides {
		position: static !important;
		width: auto !important;
		height: auto !important;

		left: 0 !important;
		top: 0 !important;
		margin-left: 0 !important;
		margin-top: 0 !important;
		padding: 0 !important;
		zoom: 1 !important;

		overflow: visible !important;
		display: block !important;

		text-align: left !important;
		-webkit-perspective: none;
		   -moz-perspective: none;
		    -ms-perspective: none;
		        perspective: none;

		-webkit-perspective-origin: 50% 50%;
		   -moz-perspective-origin: 50% 50%;
		    -ms-perspective-origin: 50% 50%;
		        perspective-origin: 50% 50%;
	}
	.reveal .slides section {
		visibility: visible !important;
		position: static !important;
		width: auto !important;
		height: auto !important;
		display: block !important;
		overflow: visible !important;

		left: 0 !important;
		top: 0 !important;
		margin-left: 0 !important;
		margin-top: 0 !important;
		padding: 60px 20px !important;
		z-index: auto !important;

		opacity: 1 !important;

		page-break-after: always !important;

		-webkit-transform-style: flat !important;
		   -moz-transform-style: flat !important;
		    -ms-transform-style: flat !important;
		        transform-style: flat !important;

		-webkit-transform: none !important;
		   -moz-transform: none !important;
		    -ms-transform: none !important;
		        transform: none !important;

		-webkit-transition: none !important;
		   -moz-transition: none !important;
		    -ms-transition: none !important;
		        transition: none !important;
	}
	.reveal .slides section.stack {
		padding: 0 !important;
	}
	.reveal section:last-of-type {
		page-break-after: avoid !important;
	}
	.reveal section .fragment {
		opacity: 1 !important;
		visibility: visible !important;

		-webkit-transform: none !important;
		   -moz-transform: none !important;
		    -ms-transform: none !important;
		        transform: none !important;
	}
	.reveal section img {
		display: block;
		margin: 15px 0px;
		background: rgba(255,255,255,1);
		border: 1px solid #666;
		box-shadow: none;
	}

	.reveal section small {
		font-size: 0.8em;
	}

}  
</script>


<script id="pdf-css" type="application/dynamic-css">
    
/**
 * This stylesheet is used to print reveal.js
 * presentations to PDF.
 *
 * https://github.com/hakimel/reveal.js#pdf-export
 */

* {
	-webkit-print-color-adjust: exact;
}

body {
	margin: 0 auto !important;
	border: 0;
	padding: 0;
	float: none !important;
	overflow: visible;
}

html {
	width: 100%;
	height: 100%;
	overflow: visible;
}

/* Remove any elements not needed in print. */
.nestedarrow,
.reveal .controls,
.reveal .progress,
.reveal .playback,
.reveal.overview,
.fork-reveal,
.share-reveal,
.state-background {
	display: none !important;
}

h1, h2, h3, h4, h5, h6 {
	text-shadow: 0 0 0 #000 !important;
}

.reveal pre code {
	overflow: hidden !important;
	font-family: Courier, 'Courier New', monospace !important;
}

ul, ol, div, p {
	visibility: visible;
	position: static;
	width: auto;
	height: auto;
	display: block;
	overflow: visible;
	margin: auto;
}
.reveal {
	width: auto !important;
	height: auto !important;
	overflow: hidden !important;
}
.reveal .slides {
	position: static;
	width: 100%;
	height: auto;

	left: auto;
	top: auto;
	margin: 0 !important;
	padding: 0 !important;

	overflow: visible;
	display: block;

	-webkit-perspective: none;
	   -moz-perspective: none;
	    -ms-perspective: none;
	        perspective: none;

	-webkit-perspective-origin: 50% 50%; /* there isn't a none/auto value but 50-50 is the default */
	   -moz-perspective-origin: 50% 50%;
	    -ms-perspective-origin: 50% 50%;
	        perspective-origin: 50% 50%;
}

.reveal .slides section {
	page-break-after: always !important;

	visibility: visible !important;
	position: relative !important;
	display: block !important;
	position: relative !important;

	margin: 0 !important;
	padding: 0 !important;
	box-sizing: border-box !important;
	min-height: 1px;

	opacity: 1 !important;

	-webkit-transform-style: flat !important;
	   -moz-transform-style: flat !important;
	    -ms-transform-style: flat !important;
	        transform-style: flat !important;

	-webkit-transform: none !important;
	   -moz-transform: none !important;
	    -ms-transform: none !important;
	        transform: none !important;
}

.reveal section.stack {
	margin: 0 !important;
	padding: 0 !important;
	page-break-after: avoid !important;
	height: auto !important;
	min-height: auto !important;
}

.reveal img {
	box-shadow: none;
}

.reveal .roll {
	overflow: visible;
	line-height: 1em;
}

/* Slide backgrounds are placed inside of their slide when exporting to PDF */
.reveal section .slide-background {
	display: block !important;
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	z-index: -1;
}

/* All elements should be above the slide-background */
.reveal section>* {
	position: relative;
	z-index: 1;
}

/* Display slide speaker notes when 'showNotes' is enabled */
.reveal .speaker-notes-pdf {
	display: block;
	width: 100%;
	max-height: none;
	left: auto;
	top: auto;
	z-index: 100;
}

/* Display slide numbers when 'slideNumber' is enabled */
.reveal .slide-number-pdf {
	display: block;
	position: absolute;
	font-size: 14px;
}

</script>


<script>
var style = document.createElement( 'style' );
style.type = 'text/css';
var style_script_id = window.location.search.match( /print-pdf/gi ) ? 'pdf-css' : 'paper-css';
var style_script = document.getElementById(style_script_id).text;
style.innerHTML = style_script;
document.getElementsByTagName('head')[0].appendChild(style);
</script>

</head>
<body>
  <div class="reveal">
    <div class="slides">

<section>
    <h1 class="title">Principal component analysis</h1>
</section>

<section id="canonical-analysis" class="slide level2">
<h2>Canonical analysis</h2>
<!-- https://www.youtube.com/watch?v=I5GxNzKLIoU -->
<ul>
<li class="fragment"><p>Family of statistical analyzes that allows to <strong>study and explore</strong> a data set of quantitative variables.</p></li>
<li class="fragment">Aimed at <strong>reducing the dimensionality</strong> of a data set while retaining much of the variation present in the data.
<ul>
<li class="fragment">Create new axes that explain most of the data variation.</li>
<li class="fragment">Project data on these new axes.</li>
</ul></li>
<li class="fragment">Visualization techniques are limited to 1D, 2D or 3D data.
<ul>
<li class="fragment">By reducing the dimensionality of data, canonical analysis make possible to plot in 2D.</li>
</ul></li>
</ul>
</section>
<section id="type-of-canonical-analysis" class="slide level2">
<h2>Type of canonical analysis</h2>
<ol type="1">
<li class="fragment"><p>Canonical Correlation Analysis (CCA)</p></li>
<li class="fragment"><p><strong>Principal Component Analysis (PCA)</strong></p></li>
<li class="fragment"><p>Linear discriminant analysis (LDA)</p></li>
<li class="fragment"><p><strong>Redundancy Analysis (RDA)</strong></p></li>
</ol>
</section>
<section id="principal-component-analysis-pca" class="slide level2">
<h2>Principal component analysis (PCA)</h2>
<ul>
<li class="fragment"><p>One of the goals behind PCA is to graphically represent the essential information contained in a (quantitative) data table.</p></li>
<li class="fragment"><p>Useful way to discover (hidden) patterns in the data by <strong>compressing</strong> data.</p></li>
<li class="fragment"><p>Not performed directly on the data but on either the <strong>covariance</strong> or <strong>correlation</strong> matrix of the data.</p></li>
</ul>
</section>
<section id="matrix-structure" class="slide level2">
<h2>Matrix structure</h2>
<p>PCA analysis is applied to rectangular data format.</p>
<p><span class="math display">\[
X_{n,p} =
 \begin{bmatrix}
  a_{1,1} &amp; a_{1,2} &amp; \cdots &amp; a_{1,p} \\
  a_{2,1} &amp; a_{2,2} &amp; \cdots &amp; a_{2,p} \\
  \vdots  &amp; \vdots  &amp; \ddots &amp; \vdots  \\
  a_{n,1} &amp; a_{n,2} &amp; \cdots &amp; a_{m,p}
 \end{bmatrix}
\]</span></p>
<p><br></p>
<p><span class="math inline">\(n\)</span> objects in the rows (<strong>observations</strong>)</p>
<p><span class="math inline">\(p\)</span> quantitative variables in the columns (<strong>variables</strong>)</p>
</section>
<section id="example-of-high-dimensional-data" class="slide level2">
<h2>Example of high dimensional data</h2>
<h4 id="mtcars-dataset">mtcars dataset</h4>
<small> <!-- html table generated in R 3.5.2 by xtable 1.8-2 package --> <!-- Mon Mar  4 15:23:10 2019 -->
<table border="1">
<tr>
<th>
</th>
<th>
mpg
</th>
<th>
cyl
</th>
<th>
disp
</th>
<th>
hp
</th>
<th>
drat
</th>
<th>
wt
</th>
<th>
qsec
</th>
</tr>
<tr>
<td align="right">
Mazda RX4
</td>
<td align="right">
21.00
</td>
<td align="right">
6.00
</td>
<td align="right">
160.00
</td>
<td align="right">
110.00
</td>
<td align="right">
3.90
</td>
<td align="right">
2.62
</td>
<td align="right">
16.46
</td>
</tr>
<tr>
<td align="right">
Mazda RX4 Wag
</td>
<td align="right">
21.00
</td>
<td align="right">
6.00
</td>
<td align="right">
160.00
</td>
<td align="right">
110.00
</td>
<td align="right">
3.90
</td>
<td align="right">
2.88
</td>
<td align="right">
17.02
</td>
</tr>
<tr>
<td align="right">
Datsun 710
</td>
<td align="right">
22.80
</td>
<td align="right">
4.00
</td>
<td align="right">
108.00
</td>
<td align="right">
93.00
</td>
<td align="right">
3.85
</td>
<td align="right">
2.32
</td>
<td align="right">
18.61
</td>
</tr>
<tr>
<td align="right">
Hornet 4 Drive
</td>
<td align="right">
21.40
</td>
<td align="right">
6.00
</td>
<td align="right">
258.00
</td>
<td align="right">
110.00
</td>
<td align="right">
3.08
</td>
<td align="right">
3.21
</td>
<td align="right">
19.44
</td>
</tr>
<tr>
<td align="right">
Hornet Sportabout
</td>
<td align="right">
18.70
</td>
<td align="right">
8.00
</td>
<td align="right">
360.00
</td>
<td align="right">
175.00
</td>
<td align="right">
3.15
</td>
<td align="right">
3.44
</td>
<td align="right">
17.02
</td>
</tr>
<tr>
<td align="right">
Valiant
</td>
<td align="right">
18.10
</td>
<td align="right">
6.00
</td>
<td align="right">
225.00
</td>
<td align="right">
105.00
</td>
<td align="right">
2.76
</td>
<td align="right">
3.46
</td>
<td align="right">
20.22
</td>
</tr>
<tr>
<td align="right">
Duster 360
</td>
<td align="right">
14.30
</td>
<td align="right">
8.00
</td>
<td align="right">
360.00
</td>
<td align="right">
245.00
</td>
<td align="right">
3.21
</td>
<td align="right">
3.57
</td>
<td align="right">
15.84
</td>
</tr>
<tr>
<td align="right">
Merc 240D
</td>
<td align="right">
24.40
</td>
<td align="right">
4.00
</td>
<td align="right">
146.70
</td>
<td align="right">
62.00
</td>
<td align="right">
3.69
</td>
<td align="right">
3.19
</td>
<td align="right">
20.00
</td>
</tr>
<tr>
<td align="right">
Merc 230
</td>
<td align="right">
22.80
</td>
<td align="right">
4.00
</td>
<td align="right">
140.80
</td>
<td align="right">
95.00
</td>
<td align="right">
3.92
</td>
<td align="right">
3.15
</td>
<td align="right">
22.90
</td>
</tr>
<tr>
<td align="right">
Merc 280
</td>
<td align="right">
19.20
</td>
<td align="right">
6.00
</td>
<td align="right">
167.60
</td>
<td align="right">
123.00
</td>
<td align="right">
3.92
</td>
<td align="right">
3.44
</td>
<td align="right">
18.30
</td>
</tr>
</table>
<p></small></p>
</section>
<section id="visualisation" class="slide level2">
<h2>Visualisation</h2>
<p>One option to visualize this dataset is to look at all pairs of correlation.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1">languageR<span class="op">::</span><span class="kw">pairscor.fnc</span>(mtcars[, <span class="dv">1</span><span class="op">:</span><span class="dv">7</span>])</a></code></pre></div>
<p><img src="06_pca_files/figure-revealjs/unnamed-chunk-2-1.svg" width="480" style="display: block; margin: auto;" /></p>
</section>
<section id="a-simple-example" class="slide level2">
<h2>A simple example</h2>
<p>The main idea of a PCA is to find out vector (also called <strong>loadings</strong> or <strong>eigenvectors</strong>) that explain most of the variation in the data.</p>
<p>For this example we will perform a PCA on two variables from the <code>mtcars</code> data set.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" data-line-number="1"><span class="co"># Extract two variables from mtcars</span></a>
<a class="sourceLine" id="cb2-2" data-line-number="2">mydata &lt;-<span class="st"> </span>mtcars[, <span class="kw">c</span>(<span class="st">&quot;mpg&quot;</span>, <span class="st">&quot;drat&quot;</span>)]</a></code></pre></div>
</section>
<section id="visualizing-the-data" class="slide level2">
<h2>Visualizing the data</h2>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1"><span class="kw">plot</span>(mydata, <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">35</span>), <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">5</span>))</a></code></pre></div>
<p><img src="06_pca_files/figure-revealjs/unnamed-chunk-4-1.svg" width="672" style="display: block; margin: auto;" /></p>
</section>
<section id="ellipse" class="slide level2">
<h2>Ellipse</h2>
<p><img src="06_pca_files/figure-revealjs/unnamed-chunk-5-1.svg" width="672" style="display: block; margin: auto;" /></p>
<p><em>How would you draw two axis that capture most of the variation?</em></p>
</section>
<section id="considerations" class="slide level2">
<h2>Considerations</h2>
<p>There are few things to keep in mind before performing a PCA.</p>
</section>
<section id="consideration-1" class="slide level2">
<h2>Consideration #1</h2>
<p>For practical reasons (i.e. to make computations easier), PCA should <strong>always</strong> be performed on <strong>mean-centered</strong> data (variables with mean = 0).</p>
<p>This simply means that mean of the variable is subtracted from each observation.</p>
<p><span class="math display">\[
\bar{X}_j = \sum_{i = 1}^{n} X_{ij} = 0
\]</span></p>
</section>
<section id="consideration-2" class="slide level2">
<h2>Consideration #2</h2>
<p>Additionally, variables should be <strong>scaled</strong> to <strong>unit-variance</strong> when <span class="math inline">\(X_1, X_2, ... X_p\)</span> are not of the same units.</p>
<p>Example:</p>
<ul>
<li><span class="math inline">\(X_1\)</span>: Age of people <span class="math inline">\((1 \leq X_1 \leq 100)\)</span></li>
<li><span class="math inline">\(X_2\)</span>: Salary income <span class="math inline">\((20 000 \$ \leq X_2 \leq 100 000 \$)\)</span></li>
</ul>
</section>
<section id="original-data" class="slide level2">
<h2>Original data</h2>
<p>Should we scale?</p>
<p><img src="06_pca_files/figure-revealjs/unnamed-chunk-6-1.svg" width="672" style="display: block; margin: auto;" /></p>
</section>
<section class="slide level2">

<p>Since we do not have same unite, we first need to scale data to zero mean and unit-variance.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" data-line-number="1">mydata_scaled &lt;-<span class="st"> </span><span class="kw">scale</span>(mydata, <span class="dt">center =</span> <span class="ot">TRUE</span>, <span class="dt">scale =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<p><img src="06_pca_files/figure-revealjs/ellipse-1.svg" width="576" style="display: block; margin: auto;" /></p>
</section>
<section class="slide level2">

<p>We can verify that the data has mean of 0.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1"><span class="kw">mean</span>(mydata_scaled<span class="op">$</span>mpg)   <span class="co"># Verify that mean is 0</span></a></code></pre></div>
<pre><code>## [1] 7.112366e-17</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1"><span class="kw">mean</span>(mydata_scaled<span class="op">$</span>drat)  <span class="co"># Verify that mean is 0</span></a></code></pre></div>
<pre><code>## [1] -2.918672e-16</code></pre>
</section>
<section class="slide level2">

<p>We can verify that the data has variance of 1.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1"><span class="kw">var</span>(mydata_scaled<span class="op">$</span>mpg)    <span class="co"># Verify that variance is 1</span></a></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1"><span class="kw">var</span>(mydata_scaled<span class="op">$</span>drat)   <span class="co"># Verify that variance is 1</span></a></code></pre></div>
<pre><code>## [1] 1</code></pre>
</section>
<section id="using-covariance-or-correlation-matrix" class="slide level2">
<h2>Using covariance or correlation matrix</h2>
<p>PCA are performed on either the <strong>covariance</strong> or <strong>correlation</strong> matrix of the data.</p>
<p>Which one to choose:</p>
<ul>
<li class="fragment"><p><strong>Covariance</strong> if the data has the same unit.</p></li>
<li class="fragment"><p><strong>Correlation</strong> if the data has not the same unit (i.e. if you scaled data to unit-variance).</p></li>
</ul>
</section>
<section id="compute-the-correlation-matrix" class="slide level2">
<h2>Compute the correlation matrix</h2>
<p>Given the data has not the same units we the first step is to calculate the correlation matrix on the variables of interest.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1">my_cor &lt;-<span class="st"> </span><span class="kw">cor</span>(mydata_scaled) <span class="co"># Correlation matrix of scaled variables</span></a>
<a class="sourceLine" id="cb13-2" data-line-number="2">my_cor <span class="co"># This is on this matrix we will perform the PCA</span></a></code></pre></div>
<pre><code>##            mpg      drat
## mpg  1.0000000 0.6811719
## drat 0.6811719 1.0000000</code></pre>
</section>
<section id="svd" class="slide level2">
<h2>SVD</h2>
<p>The next step of a PCA is to perform a singular value decomposition (SVD) on the <em>correlation/covariance</em> matrix of the data.</p>
<blockquote>
<p>SVD is a method for transforming correlated variables into a set of <strong>uncorrelated ones</strong> that better expose the various relationships among the original data items (Kirk Baker, 2013).</p>
</blockquote>
<p>We will not go into the mathematic of it, but just keep in mind that this procedure will produce vectors that are <strong>orthogonal</strong> among each others.</p>
</section>
<section id="svd-1" class="slide level2">
<h2>SVD</h2>
<p>In R, SVD can be performed using the <code>eigen()</code> function.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1"><span class="co"># Find the eigenvectors of the correlation matrix</span></a>
<a class="sourceLine" id="cb15-2" data-line-number="2">my_eigen &lt;-<span class="st"> </span><span class="kw">eigen</span>(my_cor)</a>
<a class="sourceLine" id="cb15-3" data-line-number="3"></a>
<a class="sourceLine" id="cb15-4" data-line-number="4"><span class="co"># Just renaming things so it is easier to understand</span></a>
<a class="sourceLine" id="cb15-5" data-line-number="5"><span class="kw">rownames</span>(my_eigen<span class="op">$</span>vectors) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;mpg&quot;</span>, <span class="st">&quot;drat&quot;</span>)</a>
<a class="sourceLine" id="cb15-6" data-line-number="6"><span class="kw">colnames</span>(my_eigen<span class="op">$</span>vectors) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;PC1&quot;</span>, <span class="st">&quot;PC2&quot;</span>)</a>
<a class="sourceLine" id="cb15-7" data-line-number="7"></a>
<a class="sourceLine" id="cb15-8" data-line-number="8">my_eigen</a></code></pre></div>
<pre><code>## eigen() decomposition
## $values
## [1] 1.6811719 0.3188281
## 
## $vectors
##            PC1        PC2
## mpg  0.7071068 -0.7071068
## drat 0.7071068  0.7071068</code></pre>
</section>
<section id="svd-2" class="slide level2">
<h2>SVD</h2>
<p>One important characteristic of eigenvectors/loadings is they are orthogonal (90 degree).</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" data-line-number="1"><span class="kw">cor</span>(my_eigen<span class="op">$</span>vectors) <span class="co"># Check for the correlation between PC</span></a></code></pre></div>
<pre><code>##     PC1 PC2
## PC1   1  NA
## PC2  NA   1</code></pre>
</section>
<section id="plotting-the-pc" class="slide level2">
<h2>Plotting the PC</h2>
<p>At this point, the PCA is almost done. What we need to do is to plot the new axis (PCs/eigenvectors) on the scaled data.</p>
<p><img src="06_pca_files/figure-revealjs/unnamed-chunk-13-1.svg" width="672" style="display: block; margin: auto;" /></p>
</section>
<section id="calculating-scores" class="slide level2">
<h2>Calculating scores</h2>
<p>When you perform a PCA, <strong>variables become the principal components</strong>.</p>
<p>What we want to do is to create a simple x, y plot with the newly created axes (loadings). <strong>Scores</strong> can be seen as the position of <strong>scaled</strong> data on the newly created axes (principal components).</p>
<p>This type of plot is called <strong>biplot</strong>.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" data-line-number="1"><span class="co"># Calculate the new positions of the observations on the PCs</span></a>
<a class="sourceLine" id="cb19-2" data-line-number="2">scores &lt;-<span class="st"> </span><span class="kw">as.matrix</span>(mydata_scaled) <span class="op">%*%</span><span class="st"> </span>my_eigen<span class="op">$</span>vectors</a></code></pre></div>
</section>
<section id="calculating-scores-1" class="slide level2">
<h2>Calculating scores</h2>
<p>These values are called the <strong>scores</strong>. They are the <strong><span class="math inline">\(x\)</span></strong> and <strong><span class="math inline">\(y\)</span></strong> positions of the observations on the newly created axes (PCs).</p>
<small> <!-- html table generated in R 3.5.2 by xtable 1.8-2 package --> <!-- Mon Mar  4 15:23:11 2019 -->
<table border="1">
<tr>
<th>
</th>
<th>
PC1
</th>
<th>
PC2
</th>
</tr>
<tr>
<td align="right">
Mazda RX4
</td>
<td align="right">
0.51
</td>
<td align="right">
0.29
</td>
</tr>
<tr>
<td align="right">
Mazda RX4 Wag
</td>
<td align="right">
0.51
</td>
<td align="right">
0.29
</td>
</tr>
<tr>
<td align="right">
Datsun 710
</td>
<td align="right">
0.65
</td>
<td align="right">
0.02
</td>
</tr>
<tr>
<td align="right">
Hornet 4 Drive
</td>
<td align="right">
-0.53
</td>
<td align="right">
-0.84
</td>
</tr>
<tr>
<td align="right">
Hornet Sportabout
</td>
<td align="right">
-0.75
</td>
<td align="right">
-0.43
</td>
</tr>
<tr>
<td align="right">
Valiant
</td>
<td align="right">
-1.34
</td>
<td align="right">
-0.87
</td>
</tr>
<tr>
<td align="right">
Duster 360
</td>
<td align="right">
-1.19
</td>
<td align="right">
0.17
</td>
</tr>
<tr>
<td align="right">
Merc 240D
</td>
<td align="right">
0.63
</td>
<td align="right">
-0.38
</td>
</tr>
<tr>
<td align="right">
Merc 230
</td>
<td align="right">
0.75
</td>
<td align="right">
0.11
</td>
</tr>
<tr>
<td align="right">
Merc 280
</td>
<td align="right">
0.32
</td>
<td align="right">
0.53
</td>
</tr>
</table>
<p></small></p>
</section>
<section id="biplot" class="slide level2">
<h2>Biplot</h2>
<p><img src="06_pca_files/figure-revealjs/unnamed-chunk-16-1.svg" width="960" style="display: block; margin: auto;" /></p>
</section>
<section id="explained-variance" class="slide level2">
<h2>Explained variance</h2>
<p>We know that by definition that the generated PC are capturing most of the variation in the data.</p>
<p>But how much is <em>most of the variation</em>?</p>
<p>Remember that the SVD generated eigenvectors (PC) and eigenvalues.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" data-line-number="1">my_eigen</a></code></pre></div>
<pre><code>## eigen() decomposition
## $values
## [1] 1.6811719 0.3188281
## 
## $vectors
##            PC1        PC2
## mpg  0.7071068 -0.7071068
## drat 0.7071068  0.7071068</code></pre>
</section>
<section id="explained-variance-1" class="slide level2">
<h2>Explained variance</h2>
<p><strong>An interesting property of the eigenvalues is their sum is equal to the total variance of the scaled variables.</strong></p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" data-line-number="1"><span class="co"># Sum of the generated eigenvalues</span></a>
<a class="sourceLine" id="cb22-2" data-line-number="2"><span class="kw">sum</span>(my_eigen<span class="op">$</span>values)</a></code></pre></div>
<pre><code>## [1] 2</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" data-line-number="1"><span class="co"># Total variance of the scaled data</span></a>
<a class="sourceLine" id="cb24-2" data-line-number="2"><span class="kw">var</span>(mydata_scaled<span class="op">$</span>mpg) <span class="op">+</span><span class="st"> </span><span class="kw">var</span>(mydata_scaled<span class="op">$</span>drat)</a></code></pre></div>
<pre><code>## [1] 2</code></pre>
</section>
<section id="explained-variance-2" class="slide level2">
<h2>Explained variance</h2>
<p>Hence, it becomes easy to calculate the variance explained by each PC.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" data-line-number="1">my_eigen<span class="op">$</span>values</a></code></pre></div>
<pre><code>## [1] 1.6811719 0.3188281</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" data-line-number="1">explained_variance &lt;-<span class="st"> </span>my_eigen<span class="op">$</span>values <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(my_eigen<span class="op">$</span>values)</a>
<a class="sourceLine" id="cb28-2" data-line-number="2">explained_variance</a></code></pre></div>
<pre><code>## [1] 0.840586 0.159414</code></pre>
<p>We see that PC1 accounts for 84.06% of the total variance where as PC2 explains 15.94% of the total variance.</p>
</section>
<section id="biplot-1" class="slide level2">
<h2>Biplot</h2>
<p><img src="06_pca_files/figure-revealjs/unnamed-chunk-20-1.svg" width="672" style="display: block; margin: auto;" /></p>
</section>
<section id="pca-in-r" class="slide level2">
<h2>PCA in R</h2>
</section>
<section id="pca-in-r-1" class="slide level2">
<h2>PCA in R</h2>
<!-- http://www.davidzeleny.net/anadat-r/doku.php/en:pca -->
<p>There are many packages to perform PCA in R.</p>
<p>They are probably all good, but I recommend to use the <code>rda()</code> function from the <code>vegan</code> package.</p>
<p>The package is not included in base R, so you have to install it using the following code:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" data-line-number="1"><span class="kw">install.packages</span>(<span class="st">&quot;vegan&quot;</span>)</a>
<a class="sourceLine" id="cb30-2" data-line-number="2"><span class="kw">library</span>(vegan)</a></code></pre></div>
</section>
<section id="pca-in-r-2" class="slide level2">
<h2>PCA in R</h2>
<p>We will use the same data to see if we can obtain the same results with <code>vegan</code>.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" data-line-number="1"><span class="kw">head</span>(mydata)</a></code></pre></div>
<pre><code>##                    mpg drat
## Mazda RX4         21.0 3.90
## Mazda RX4 Wag     21.0 3.90
## Datsun 710        22.8 3.85
## Hornet 4 Drive    21.4 3.08
## Hornet Sportabout 18.7 3.15
## Valiant           18.1 2.76</code></pre>
</section>
<section id="pca-in-r-3" class="slide level2">
<h2>PCA in R</h2>
<p>A PCA is performed using the <code>rda()</code> function. It is a bit confusing since it is the same function for performing redundancy analysis.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" data-line-number="1"><span class="kw">library</span>(vegan)</a>
<a class="sourceLine" id="cb33-2" data-line-number="2">my_pca &lt;-<span class="st"> </span><span class="kw">rda</span>(mydata, <span class="dt">scale =</span> <span class="ot">TRUE</span>) <span class="co"># Do not forget to scale!</span></a>
<a class="sourceLine" id="cb33-3" data-line-number="3">my_pca</a></code></pre></div>
<pre><code>## Call: rda(X = mydata, scale = TRUE)
## 
##               Inertia Rank
## Total               2     
## Unconstrained       2    2
## Inertia is correlations 
## 
## Eigenvalues for unconstrained axes:
##    PC1    PC2 
## 1.6812 0.3188</code></pre>
</section>
<section id="pca-in-r-4" class="slide level2">
<h2>PCA in R</h2>
<p>Lets compare preliminary results from vegan with those we manually calculated earlier.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" data-line-number="1">my_pca <span class="co"># Vegan results</span></a></code></pre></div>
<pre><code>## Call: rda(X = mydata, scale = TRUE)
## 
##               Inertia Rank
## Total               2     
## Unconstrained       2    2
## Inertia is correlations 
## 
## Eigenvalues for unconstrained axes:
##    PC1    PC2 
## 1.6812 0.3188</code></pre>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" data-line-number="1">my_eigen<span class="op">$</span>values <span class="co"># Manually calculated results</span></a></code></pre></div>
<pre><code>## [1] 1.6811719 0.3188281</code></pre>
</section>
<section id="biplot-in-r" class="slide level2">
<h2>Biplot in R</h2>
<p>Biplot of a PCA can be easily plotted using the <code>biplot()</code> function.</p>
</section>
<section id="biplot-in-r-1" class="slide level2">
<h2>Biplot in R</h2>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb39-1" data-line-number="1"><span class="kw">biplot</span>(my_pca)</a></code></pre></div>
<p><img src="06_pca_files/figure-revealjs/unnamed-chunk-25-1.svg" width="672" style="display: block; margin: auto;" /></p>
</section>
<section id="a-more-complicated-example" class="slide level2">
<h2>A more complicated example</h2>
<p>Lets do a PCA with more more variable (i.e. more dimensions).</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" data-line-number="1">mydata &lt;-<span class="st"> </span><span class="kw">head</span>(mtcars[, <span class="dv">1</span><span class="op">:</span><span class="dv">7</span>])</a>
<a class="sourceLine" id="cb40-2" data-line-number="2">mydata</a></code></pre></div>
<pre><code>##                    mpg cyl disp  hp drat    wt  qsec
## Mazda RX4         21.0   6  160 110 3.90 2.620 16.46
## Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02
## Datsun 710        22.8   4  108  93 3.85 2.320 18.61
## Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44
## Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02
## Valiant           18.1   6  225 105 2.76 3.460 20.22</code></pre>
</section>
<section id="the-pca" class="slide level2">
<h2>The PCA</h2>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb42-1" data-line-number="1">my_pca &lt;-<span class="st"> </span><span class="kw">rda</span>(mtcars[, <span class="dv">1</span><span class="op">:</span><span class="dv">7</span>], <span class="dt">scale =</span> <span class="ot">TRUE</span>) <span class="co"># Do not forget to scale!</span></a>
<a class="sourceLine" id="cb42-2" data-line-number="2">my_pca <span class="co"># 7 PC generated</span></a></code></pre></div>
<pre><code>## Call: rda(X = mtcars[, 1:7], scale = TRUE)
## 
##               Inertia Rank
## Total               7     
## Unconstrained       7    7
## Inertia is correlations 
## 
## Eigenvalues for unconstrained axes:
##   PC1   PC2   PC3   PC4   PC5   PC6   PC7 
## 5.086 1.157 0.345 0.158 0.129 0.076 0.049</code></pre>
</section>
<section id="the-pca-1" class="slide level2">
<h2>The PCA</h2>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb44-1" data-line-number="1"><span class="kw">summary</span>(my_pca)</a></code></pre></div>
<pre><code>## 
## Call:
## rda(X = mtcars[, 1:7], scale = TRUE) 
## 
## Partitioning of correlations:
##               Inertia Proportion
## Total               7          1
## Unconstrained       7          1
## 
## Eigenvalues, and their contribution to the correlations 
## 
## Importance of components:
##                          PC1    PC2     PC3     PC4    PC5     PC6
## Eigenvalue            5.0861 1.1566 0.34485 0.15793 0.1295 0.07586
## Proportion Explained  0.7266 0.1652 0.04926 0.02256 0.0185 0.01084
## Cumulative Proportion 0.7266 0.8918 0.94107 0.96364 0.9821 0.99297
##                            PC7
## Eigenvalue            0.049198
## Proportion Explained  0.007028
## Cumulative Proportion 1.000000
## 
## Scaling 2 for species and site scores
## * Species are scaled proportional to eigenvalues
## * Sites are unscaled: weighted dispersion equal on all dimensions
## * General scaling constant of scores:  3.838088 
## 
## 
## Species scores
## 
##          PC1     PC2     PC3       PC4      PC5      PC6
## mpg  -1.3504  0.1294 -0.2059 -0.442063  0.11108  0.03597
## cyl   1.3895  0.1224 -0.1602 -0.111800 -0.12444 -0.31186
## disp  1.3823 -0.1286  0.1006 -0.338800 -0.07772  0.06461
## hp    1.2686  0.5257  0.1727  0.003969  0.43404 -0.01841
## drat -1.0835  0.6998  0.6434 -0.067493 -0.11576 -0.09317
## wt    1.2802 -0.5029  0.3753 -0.061886 -0.08699  0.14628
## qsec -0.7849 -1.1690  0.2508 -0.035387  0.17113 -0.16276
## 
## 
## Site scores (weighted sums of species scores)
## 
##                           PC1       PC2      PC3      PC4      PC5
## Mazda RX4           -0.243242  0.579894 -0.30711  0.49108 -1.11434
## Mazda RX4 Wag       -0.235052  0.375523 -0.06404  0.40918 -1.00074
## Datsun 710          -0.625323 -0.033350 -0.08749  0.84325  0.13668
## Hornet 4 Drive      -0.043821 -0.825952 -0.68534 -0.38259  0.19179
## Hornet Sportabout    0.490303  0.008421 -0.69878 -0.91626 -0.20639
## Valiant              0.040751 -1.290237 -0.83456  0.64467  0.37678
## Duster 360           0.756378  0.512097 -0.30871  0.08974  0.61740
## Merc 240D           -0.592484 -0.776765  0.23619 -0.02117 -0.23256
## Merc 230            -0.675542 -1.331752  1.34052  0.13367  1.28885
## Merc 280            -0.154230 -0.055250  0.65363  0.55479 -0.58838
## Merc 280C           -0.149548 -0.228874  0.83555  0.82801 -0.47222
## Merc 450SE           0.535921 -0.238442 -0.39350  0.17258 -0.06050
## Merc 450SL           0.467311 -0.212458 -0.57688  0.02675  0.18159
## Merc 450SLC          0.500967 -0.349059 -0.37426  0.45684  0.16381
## Cadillac Fleetwood   1.056127 -0.776612  0.69870 -0.31860 -0.40694
## Lincoln Continental  1.075495 -0.696090  0.89710 -0.26832 -0.31563
## Chrysler Imperial    0.953786 -0.354488  0.98670 -1.09866  0.07216
## Fiat 128            -0.996997 -0.103343 -0.18151 -1.15484  0.38481
## Honda Civic         -1.175905  0.672184  0.77724 -0.84613 -0.88707
## Toyota Corolla      -1.126816 -0.053228 -0.14169 -1.43287  0.63949
## Toyota Corona       -0.589920 -0.524964  0.09976  0.97728  0.67769
## Dodge Challenger     0.560080 -0.266981 -1.31533  0.27287 -0.67591
## AMC Javelin          0.449899 -0.151555 -0.63193  0.29666 -0.79499
## Camaro Z28           0.719098  0.845740  0.64899  0.16942 -0.07955
## Pontiac Firebird     0.583046 -0.135449 -0.57381 -1.40788 -0.33059
## Fiat X1-9           -0.898925  0.060701 -0.19144  0.05260 -0.07467
## Porsche 914-2       -0.736374  0.846646  0.26597 -0.03670 -0.79493
## Lotus Europa        -0.776611  0.689230 -1.28006 -0.43856  0.87092
## Ford Pantera L       0.563327  1.576823  0.88082 -0.39160  0.03812
## Ferrari Dino        -0.008548  0.855360 -0.60774  1.04767  0.17839
## Maserati Bora        0.824243  1.337699  0.21219  0.38475  2.19332
## Volvo 142E          -0.547393  0.044529  0.72081  0.86238  0.02361
##                          PC6
## Mazda RX4           -0.02832
## Mazda RX4 Wag       -0.10902
## Datsun 710           0.63247
## Hornet 4 Drive       0.05870
## Hornet Sportabout   -0.49123
## Valiant             -0.03029
## Duster 360          -0.04395
## Merc 240D            1.06715
## Merc 230            -1.01059
## Merc 280            -0.39638
## Merc 280C           -0.79105
## Merc 450SE          -0.40004
## Merc 450SL          -0.79893
## Merc 450SLC         -1.05883
## Cadillac Fleetwood   0.90127
## Lincoln Continental  1.02310
## Chrysler Imperial    0.99648
## Fiat 128             0.08697
## Honda Civic         -0.90773
## Toyota Corolla      -0.62008
## Toyota Corona        0.11740
## Dodge Challenger    -0.11973
## AMC Javelin         -0.92732
## Camaro Z28          -0.18341
## Pontiac Firebird     0.09667
## Fiat X1-9           -0.02567
## Porsche 914-2        1.08370
## Lotus Europa         1.14803
## Ford Pantera L      -0.76179
## Ferrari Dino         0.75862
## Maserati Bora       -0.01456
## Volvo 142E           0.74836</code></pre>
</section>
<section id="correlation-between-pc" class="slide level2">
<h2>Correlation between PC</h2>
<p>As already stated, all principal component are orthogonal to each other.</p>
<table>
<caption>Correlation coefficients between PC.</caption>
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">PC1</th>
<th style="text-align: right;">PC2</th>
<th style="text-align: right;">PC3</th>
<th style="text-align: right;">PC4</th>
<th style="text-align: right;">PC5</th>
<th style="text-align: right;">PC6</th>
<th style="text-align: right;">PC7</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>PC1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td>PC2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td>PC3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td>PC4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td>PC5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td>PC6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td>PC7</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</section>
<section id="selecting-pca-axes" class="slide level2">
<h2>Selecting PCA axes</h2>
<ul>
<li>As we just saw, seven PC were generated.</li>
<li>Since we are limited to plot into only 2D, we have to decide which PC to keep for the visualization.</li>
<li>There are many ways to determine with PC are important which are review in <span class="citation" data-cites="Peres-Neto2005">Peres-Neto, Jackson, and Somers (2005)</span>.</li>
<li>Today we will focus on the <strong>Kaiser-Guttman criterion</strong>.</li>
</ul>
</section>
<section id="kaiser-guttman-criteria" class="slide level2">
<h2>Kaiser-Guttman criteria</h2>
<p>The Kaiser-Guttman criteria simply says that PC with eigenvalues higher than the average of all eigenvalues should be kept.</p>
<p>We can use the <code>screeplot()</code> function to have a graphical overview of all eigenvalues.</p>
</section>
<section class="slide level2">

<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" data-line-number="1"><span class="co"># plot the screeplot</span></a>
<a class="sourceLine" id="cb46-2" data-line-number="2"><span class="kw">screeplot</span>(my_pca)</a>
<a class="sourceLine" id="cb46-3" data-line-number="3"></a>
<a class="sourceLine" id="cb46-4" data-line-number="4"><span class="co"># add a line representing mean value of all eigenvalues</span></a>
<a class="sourceLine" id="cb46-5" data-line-number="5"><span class="kw">abline</span>(<span class="dt">h =</span> <span class="kw">mean</span>(my_pca<span class="op">$</span>CA<span class="op">$</span>eig), <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>) </a></code></pre></div>
<p><img src="06_pca_files/figure-revealjs/unnamed-chunk-30-1.svg" width="480" style="display: block; margin: auto;" /></p>
<p>Based on this graph, it seems that the first two PC are important.</p>
</section>
<section id="biplot-2" class="slide level2">
<h2>Biplot</h2>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" data-line-number="1"><span class="kw">biplot</span>(my_pca, <span class="dt">choices =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>)) <span class="co"># Selecting axes 1 and 2</span></a></code></pre></div>
<p><img src="06_pca_files/figure-revealjs/unnamed-chunk-31-1.svg" width="672" style="display: block; margin: auto;" /></p>
</section>
<section id="selecting-different-axes" class="slide level2">
<h2>Selecting different axes</h2>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb48-1" data-line-number="1"><span class="kw">biplot</span>(my_pca, <span class="dt">choices =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">3</span>)) <span class="co"># Selecting axes 1 and 3</span></a></code></pre></div>
<p><img src="06_pca_files/figure-revealjs/unnamed-chunk-32-1.svg" width="672" style="display: block; margin: auto;" /></p>
</section>
<section id="interpreting-a-pca" class="slide level2">
<h2>Interpreting a PCA</h2>
<h4 id="angle-between-variables">Angle between variables</h4>
<p>Look at the angle between <code>qsec</code> and <code>wt</code> (~90 degrees).</p>
<p><img src="06_pca_files/figure-revealjs/unnamed-chunk-33-1.svg" width="672" style="display: block; margin: auto;" /></p>
</section>
<section id="your-turn" class="slide level2">
<h2>Your turn!</h2>
<p>Using your data (or a subset of your data) and perform a PCA. What does this tell you about your data?</p>
</section>
<section id="useful-resources" class="slide level2">
<h2>Useful resources</h2>
<p><small></p>
<p><a href="https://www.ling.ohio-state.edu/~kbaker/pubs/Singular_Value_Decomposition_Tutorial.pdf" class="uri">https://www.ling.ohio-state.edu/~kbaker/pubs/Singular_Value_Decomposition_Tutorial.pdf</a></p>
<p><a href="http://www.davidzeleny.net/anadat-r/doku.php/en:pca" class="uri">http://www.davidzeleny.net/anadat-r/doku.php/en:pca</a></p>
<p></small></p>
</section>
<section id="references" class="slide level2 unnumbered refsection">
<h2>References</h2>
<div id="refs" class="references">
<div id="ref-Peres-Neto2005">
<p>Peres-Neto, Pedro R., Donald A. Jackson, and Keith M. Somers. 2005. “How many principal components? stopping rules for determining the number of non-trivial axes revisited.” <em>Comput. Stat. Data Anal.</em> 49 (4): 974–97. <a href="https://doi.org/10.1016/j.csda.2004.06.015">https://doi.org/10.1016/j.csda.2004.06.015</a>.</p>
</div>
</div>
</section>
    </div>
  </div>

  <script src="06_pca_files/reveal.js-3.3.0.1/lib/js/head.min.js"></script>
  <script src="06_pca_files/reveal.js-3.3.0.1/js/reveal.js"></script>

  <script>

      // Full list of configuration options available at:
      // https://github.com/hakimel/reveal.js#configuration
      Reveal.initialize({
        // Push each slide change to the browser history
        history: true,
        // Vertical centering of slides
        center: true,
        // Transition style
        transition: 'convex', // none/fade/slide/convex/concave/zoom
        // Transition style for full page slide backgrounds
        backgroundTransition: 'default', // none/fade/slide/convex/concave/zoom



        // Optional reveal.js plugins
        dependencies: [
        ]
      });
    </script>
  <!-- dynamically load mathjax for compatibility with self-contained -->
  <script>
    (function () {
      var script = document.createElement("script");
      script.type = "text/javascript";
      script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
      document.getElementsByTagName("head")[0].appendChild(script);
    })();
  </script>

<script>
  (function() {
    if (window.jQuery) {
      Reveal.addEventListener( 'slidechanged', function(event) {  
        window.jQuery(event.previousSlide).trigger('hidden');
        window.jQuery(event.currentSlide).trigger('shown');
      });
    }
  })();
</script>


  </body>
</html>
