theme: jekyll-theme-minimal

title: [Numerical ecology - Basic data handling and statistics using R]
description: [Teaching material for the lecture week (Aarhus University, Campus Roskilde)]

# Includes an icon in the footer for each username you enter
footer-links:
  twitter: philmassicotte